
# API Authentication basic configuration
server:
 port: 8081
spring:
 application:
  name: dopost-auth-api

# MongoDB configuration
 data:
  mongodb:
   uri: mongodb://${MONGO_USER}:${MONGO_PASS}@${MONGO_HOST}:${MONGO_PORT}/dopost_ws?authSource=admin

# Context Path
dopost:
 auth:
  context:
   path: /dopost-auth/api
   
  